#!/bin/bash

# This wrapper is needed to allow polybar to plot the battery percentage
while [ true ]; do
    battery=`/home/perseo/scripts/hyperx-get-battery-headset`
    echo ${battery}%
    sleep 1
done &

wait
